server:
  port: 8989

spring:
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

myoss:
  xxaccessKey: 67l-W3jIkMzW3JMFuc8odhiC2MKR7E-3ArdHaE2l
  xxsecretKey: 26tIZn1J7NxwV0B-ZTMwslR5_kyoflRp3krJgtFq
  xxbucket: hikari-blog